[cursor]
thickness = 0.2
unfocused_hollow = true
[cursor.style]
blinking = "Off"
shape = "Block"

[font]
size = 13
[font.bold]
family = "Comic Mono"

[font.bold_italic]
family = "Comic Mono"

[font.italic]
family = "Comic Mono"

[font.normal]
family = "Comic Mono"

[mouse]
hide_when_typing = true

# Source https//github.com/zatchheems/tokyo-night-alacritty-theme
# Default colors
[colors.primary]
background = '#1a1b26'
foreground = '#a9b1d6'

# Normal colors
[colors.normal]
black   = '#32344a'
red     = '#f7768e'
green   = '#9ece6a'
yellow  = '#e0af68'
blue    = '#7aa2f7'
magenta = '#ad8ee6'
cyan    = '#449dab'
white   = '#787c99'

# Bright colors
[colors.bright]
black   = '#444b6a'
red     = '#ff7a93'
green   = '#b9f27c'
yellow  = '#ff9e64'
blue    = '#7da6ff'
magenta = '#bb9af7'
cyan    = '#0db9d7'
white   = '#acb0d0'
