theme = "catppuccin_mocha"

[editor]
line-number = "absolute"
mouse = true
scrolloff = 10
middle-click-paste = true
scroll-lines = 6
cursorline = true
auto-completion = true 
auto-format = true 
bufferline = "never"

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-base-name"]
right = [ "total-line-numbers", "file-type"]
separator = "│"
mode.normal = "norm"
mode.insert = "I"
mode.select = "visual"


[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
